### ISSUE TITLE
Markdown images pointing to the images/ directory

### ISSUE THREAD

**Issue by louis-smit** [oban-bg/oban_training#1]
Hi all. I am _very_ much looking forward to going through these LiveBooks as a long time Oban fan. However, on opening the `start.livemd` I get the following error:

```
found Markdown images pointing to the images/ directory. Using this directory has been deprecated, please use notebook files instead
```

And as indicated by the error the images on `00_introduction.livemd` are not displaying. This doesn't really affect the overall experience of the LiveBooks of course, but I just thought I'd put this here for reference.

Using `MacOS Sonoma 14.1`, `LiveBook 0.13.3` and `Elixir 1.17.1`.

Thanks again for all your hard work on Oban and these LiveBooks!

**Comment by sorentwo** [comment]
Thanks for the report; we missed a couple of images during the LiveBook update. It's fixed up now!
